#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xcmiscproto
Version  : 1.2.2
Release  : 3
URL      : http://xorg.freedesktop.org/releases/individual/proto/xcmiscproto-1.2.2.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/proto/xcmiscproto-1.2.2.tar.gz
Summary  : XCMisc extension headers
Group    : Development/Tools
License  : MIT
Requires: xcmiscproto-doc
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : xmlto

%description
XC-MISC Extension
This extension defines a protocol that provides Xlib two ways to query
the server for available resource IDs.

%package dev
Summary: dev components for the xcmiscproto package.
Group: Development

%description dev
dev components for the xcmiscproto package.


%package doc
Summary: doc components for the xcmiscproto package.
Group: Documentation

%description doc
doc components for the xcmiscproto package.


%prep
%setup -q -n xcmiscproto-1.2.2

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/xcmiscproto.h
/usr/include/X11/extensions/xcmiscstr.h
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/xcmiscproto/*
